
 {
function BxDolPage(oOptions){this._sObjName=oOptions.sObjName==undefined?'oBxDolPage':oOptions.sObjName;this._sObject=oOptions.sObject;this._sActionsUri='page.php';this._sActionsUrl=oOptions.sRootUrl;this._aHtmlIds=oOptions.aHtmlIds;this._isStickyColumns=oOptions.isStickyColumns==undefined?!1:oOptions.isStickyColumns;this._iLastSc=0;var $this=this;$(document).ready(function(){$this.init()})}
BxDolPage.prototype.init=function(){var $this=this;if($this._isStickyColumns&&!$('html').hasClass('bx-media-phone')){$('.bx-layout-cell').addClass('sticky top-4')}
$(".bx-embed-link").each(function(){$(this).html($(this).attr('source'));$.getJSON(sUrlRoot+'/embed.php?',{a:'get_link',l:$(this).attr('source')},$this.embededCallback($(this)))});bx_process_links()};BxDolPage.prototype.embededCallback=function(item){return function(oData){item.html(oData.code)
if(item.find('a').length>0){bx_embed_link(item.find('a')[0])}}}
BxDolPage.prototype.share=function(oLink,sUrl){var oData=this._getDefaultParams();oData.a='get_share';oData.url=sUrl;$(".bx-popup-applied:visible").dolPopupHide();$(window).dolPopupAjax({url:bx_append_url_params(this._sActionsUri,oData),displayMode:'box',closeOnOuterClick:!1,id:{value:'sys_share_popup',force:!0}})}
BxDolPage.prototype.showHelp=function(oLink,iBlockId){var oData=this._getDefaultParams();oData.a='get_help';oData.block_id=iBlockId;$(oLink).dolPopupAjax({id:{value:this._aHtmlIds.help_popup+iBlockId,force:1},url:bx_append_url_params(this._sActionsUri,oData),closeOnOuterClick:!0,removeOnClose:!0,onBeforeShow:function(oPopup){oPopup.addClass('bx-popup-help')}})};BxDolPage.prototype._getDefaultParams=function(){var oDate=new Date();return{o:this._sObject,_t:oDate.getTime()}}
 }

/*--- BEGIN: http://localhost/UNA-v.13.0.0-RC2//plugins_public/theia-sticky-sidebar/ResizeSensor.min.js---*/
!function(){var e=function(t,i){function s(){this.q=[],this.add=function(e){this.q.push(e)};var e,t;this.call=function(){for(e=0,t=this.q.length;e<t;e++)this.q[e].call()}}function o(e,t){return e.currentStyle?e.currentStyle[t]:window.getComputedStyle?window.getComputedStyle(e,null).getPropertyValue(t):e.style[t]}function n(e,t){if(e.resizedAttached){if(e.resizedAttached)return void e.resizedAttached.add(t)}else e.resizedAttached=new s,e.resizedAttached.add(t);e.resizeSensor=document.createElement("div"),e.resizeSensor.className="resize-sensor";var i="position: absolute; left: 0; top: 0; right: 0; bottom: 0; overflow: hidden; z-index: -1; visibility: hidden;",n="position: absolute; left: 0; top: 0; transition: 0s;";e.resizeSensor.style.cssText=i,e.resizeSensor.innerHTML='<div class="resize-sensor-expand" style="'+i+'"><div style="'+n+'"></div></div><div class="resize-sensor-shrink" style="'+i+'"><div style="'+n+' width: 200%; height: 200%"></div></div>',e.appendChild(e.resizeSensor),{fixed:1,absolute:1}[o(e,"position")]||(e.style.position="relative");var d,r,l=e.resizeSensor.childNodes[0],c=l.childNodes[0],h=e.resizeSensor.childNodes[1],a=(h.childNodes[0],function(){c.style.width=l.offsetWidth+10+"px",c.style.height=l.offsetHeight+10+"px",l.scrollLeft=l.scrollWidth,l.scrollTop=l.scrollHeight,h.scrollLeft=h.scrollWidth,h.scrollTop=h.scrollHeight,d=e.offsetWidth,r=e.offsetHeight});a();var f=function(){e.resizedAttached&&e.resizedAttached.call()},u=function(e,t,i){e.attachEvent?e.attachEvent("on"+t,i):e.addEventListener(t,i)},p=function(){e.offsetWidth==d&&e.offsetHeight==r||f(),a()};u(l,"scroll",p),u(h,"scroll",p)}var d=Object.prototype.toString.call(t),r="[object Array]"===d||"[object NodeList]"===d||"[object HTMLCollection]"===d||"undefined"!=typeof jQuery&&t instanceof jQuery||"undefined"!=typeof Elements&&t instanceof Elements;if(r)for(var l=0,c=t.length;l<c;l++)n(t[l],i);else n(t,i);this.detach=function(){if(r)for(var i=0,s=t.length;i<s;i++)e.detach(t[i]);else e.detach(t)}};e.detach=function(e){e.resizeSensor&&(e.removeChild(e.resizeSensor),delete e.resizeSensor,delete e.resizedAttached)},"undefined"!=typeof module&&"undefined"!=typeof module.exports?module.exports=e:window.ResizeSensor=e}();

 {
function BxDolLiveUpdates(oOptions){this._sActionsUrl=oOptions.sActionsUrl==undefined?sUrlRoot+'live_updates.php':oOptions.sActionsUrl;this._sObjName=oOptions.sObjName==undefined?'oLiveUpdates':oOptions.sObjName;this._iInterval=oOptions.iInterval==undefined?3000:oOptions.iInterval;this._aSystemsActive=oOptions.aSystemsActive==undefined?{}:oOptions.aSystemsActive;this._aSystemsTransient=oOptions.aSystemsTransient==undefined?{}:oOptions.aSystemsTransient;this._bServerRequesting=oOptions.bServerRequesting==undefined?!1:oOptions.bServerRequesting;this._sHash=oOptions.sHash==undefined?'':oOptions.sHash;this._iIndex=0;this._iHandler=0;this._bBusy=!1;this.init()}
BxDolLiveUpdates.prototype.init=function(){var $this=this;if(this._iHandler)
this.destroy();$(document).ready(function(){$this.perform();$this._iHandler=setInterval(function(){$this.perform()},$this._iInterval)})};BxDolLiveUpdates.prototype.add=function(oData){if(!oData)
return;if(oData.name!=undefined&&oData.value!=undefined){if(!this._aSystemsActive[oData.name])
this._aSystemsActive[oData.name]=oData.value;if(!this._aSystemsTransient[oData.name])
this._aSystemsTransient[oData.name]=1}
if(oData.hash!=undefined)
this._sHash=oData.hash};BxDolLiveUpdates.prototype.destroy=function(){if(this._iHandler)
clearInterval(this._iHandler);};BxDolLiveUpdates.prototype.perform=function(){if(!this._bServerRequesting||this._bBusy||('undefined'!==typeof(document.hidden)&&document.hidden))
return;var $this=this;var oDate=new Date();this._bBusy=!0;$.post(this._sActionsUrl,{index:this._iIndex,systems_active:this._aSystemsActive,systems_transient:this._aSystemsTransient,hash:this._sHash,_t:oDate.getTime()},function(aData){$.each(aData,function(iIndex,oValue){if(oValue.system&&$this._aSystemsActive[oValue.system]!=undefined&&oValue.data)
$this._aSystemsActive[oValue.system]=oValue.data.count_new;if(oValue.method){var oFunc=function(oData){eval(oValue.method)};oFunc(oValue.data)}});$this._bBusy=!1},'json');this._iIndex+=1}
 }
