
 {
function BxDolCreatePost(oOptions){this._sObjName=oOptions.sObjName==undefined?'oBxDolCreatePost':oOptions.sObjName;this._sRootUrl=oOptions.sRootUrl==undefined?sUrlRoot:oOptions.sRootUrl;this._sDefault=oOptions.sDefault==undefined?'':oOptions.sDefault;this._iContextId=oOptions.iContextId==undefined?0:oOptions.iContextId;this._oPreloadingList=oOptions.oPreloadingList==undefined?[]:oOptions.oPreloadingList;this._oCustom=oOptions.oCustom==undefined?{}:oOptions.oCustom;this._sAnimationEffect=oOptions.sAnimationEffect==undefined?'fade':oOptions.sAnimationEffect;this._iAnimationSpeed=oOptions.iAnimationSpeed==undefined?'slow':oOptions.iAnimationSpeed;this._aHtmlIds=oOptions.aHtmlIds==undefined?{}:oOptions.aHtmlIds;var $this=this;$(document).ready(function(){$this.init()})}
BxDolCreatePost.prototype.init=function(){var oDate=new Date();for(var sKey in this._oPreloadingList){var sForm='.sys-cpf-form.sys-cpf-'+sKey;if($(sForm).length!=0)
continue;$.get(this._sRootUrl+'modules/?r='+this._oPreloadingList[sKey]+'/get_create_post_form/',{ajax_mode:!0,dynamic_mode:!0,absolute_action_url:!0,context_id:this._iContextId,custom:this._oCustom,_t:oDate.getTime()},function(oData){if(!oData||!oData.content)
return;$('.sys-cpf-close').before($('<div class="sys-cpf-form sys-cpf-'+oData.module+'">'+oData.content+'</div>').hide())},'json')}};BxDolCreatePost.prototype.getForm=function(sModuleName,sModuleUri,oElement){var $this=this;var oTab=$(oElement);var sTabActive='bx-menu-tab-active';oTab.parents('.bx-db-menu:first').find('li.'+sTabActive).removeClass(sTabActive);oTab.parents('li:first').addClass(sTabActive);oTab.parents('.bx-popup-applied:visible').dolPopupHide();$('.sys-cpf-form:visible').hide({duration:0,complete:function(){$('.sys-cpf-close:visible').hide();if(!$('.sys-cpf-form.sys-cpf-'+sModuleName+' form').length){var oDate=new Date();$this._placeholderInBlock(oElement,!0);$.get($this._sRootUrl+'modules/?r='+sModuleUri+'/get_create_post_form/',{ajax_mode:!0,dynamic_mode:!0,absolute_action_url:!0,context_id:$this._iContextId,custom:$this._oCustom,_t:oDate.getTime()},function(oData){$this._placeholderInBlock(oElement,!1);if(!oData||!oData.content)
return;var sForm='.sys-cpf-form.sys-cpf-'+oData.module;if($(sForm).length==0)
$('.sys-cpf-close').before($('<div class="sys-cpf-form sys-cpf-'+oData.module+'"></div>').hide());$(sForm).html(oData.content).show().siblings('.sys-cpf-close:hidden').show()},'json')}else $('.sys-cpf-form.sys-cpf-'+sModuleName).show().siblings('.sys-cpf-close:hidden').show()}});return!1};BxDolCreatePost.prototype.hideForm=function(oElement){$(oElement).parents('.sys-cpf-close:first').hide();var sTabActive='bx-menu-tab-active';var sTabDefault='bx-menu-item-'+this._sDefault;var oMiActive=$(oElement).parents('.bx-db-container:first').find('ul > li.'+sTabActive);var bMiChange=!oMiActive.hasClass(sTabDefault);if(bMiChange)
oMiActive.removeClass(sTabActive);$('.sys-cpf-form:visible').hide({duration:0,complete:function(){$('.sys-cpf-form.sys-cpf-default').show();if(bMiChange)
$('.'+sTabDefault).addClass(sTabActive);}})};BxDolCreatePost.prototype._loading=function(e,bShow){var oParent=$(e).length?$(e):$('body');bx_loading(oParent,bShow)};BxDolCreatePost.prototype._loadingInBlock=function(e,bShow){var oParent=$(e).length?$(e).parents('.bx-db-container:first'):$('body');bx_loading(oParent,bShow)};BxDolCreatePost.prototype._placeholderInBlock=function(e,bShow){var oPlaceholder=null;if($(e).length)
oPlaceholder=$(e).parents('.bx-db-container:first').find('.sys-cpf-form.sys-cpf-loading');if(!oPlaceholder)
return _loadingInBlock(e,bShow);if(bShow)
oPlaceholder.show();else oPlaceholder.hide()}
 }

 {
function bx_base_general_select_thumb(eCheckbox){bx_base_general_select_ghost(eCheckbox,'thumb')}
function bx_base_general_select_ghost(eCheckbox,sName){var eCont=$(eCheckbox).parents('.bx-form-input-files-result');if(!eCont.length)
return;eCont.find('.bx-base-general-use-as-'+sName+' input:checked').each(function(){if($(this).prop('id')!=$(eCheckbox).prop('id'))
$(this).prop('checked',!1);})}
function bx_base_general_delete_ghost(iFileId,sFileUrl,sFileIcon,aEditors,oUploaderInstance){if('undefined'!==typeof(bx_editor_remove_img)){bx_editor_remove_img(aEditors,['img[src="'+sFileIcon+'"]','img[src="'+sFileUrl+'"]','#bx-base-general-img-'+iFileId,'.bx-base-general-icon-'+iFileId])}
oUploaderInstance.deleteGhost(iFileId)}
function bx_base_general_insert_to_post(iFileId,sFileUrl,sEditorId,sMimeType,sEmbedBaseUrl){if('undefined'!==typeof(sMimeType)&&sMimeType.startsWith('video/')&&'undefined'!==typeof(sEmbedBaseUrl))
bx_base_general_insert_video_embed(sEditorId,'bx-base-general-img-'+iFileId,sEmbedBaseUrl+iFileId,'bx-base-general-img');else if('undefined'!==typeof(sMimeType)&&sMimeType.startsWith('audio/')&&'undefined'!==typeof(sEmbedBaseUrl))
bx_base_general_insert_audio_embed(sEditorId,'bx-base-general-img-'+iFileId,sEmbedBaseUrl+iFileId,'bx-base-general-img');else bx_editor_insert_img(sEditorId,'bx-base-general-img-'+iFileId,sFileUrl,'bx-base-general-img')}
function bx_base_general_insert_video_embed(sEditorId,sHtmlId,sEmbedUrl,sClass){bx_editor_insert_html(sEditorId,sHtmlId,'<iframe width="560" height="315" src="'+sEmbedUrl+'" frameborder="0" allow="autoplay; picture-in-picture" allowfullscreen></iframe>')}
function bx_base_general_insert_audio_embed(sEditorId,sHtmlId,sEmbedUrl,sClass){bx_editor_insert_html(sEditorId,sHtmlId,'<iframe width="320" height="52" src="'+sEmbedUrl+'" frameborder="0" allow="autoplay; picture-in-picture" allowfullscreen></iframe>')}
 }

 {
function BxTimelinePost(oOptions){this._sActionsUri=oOptions.sActionUri;this._sActionsUrl=oOptions.sActionUrl;this._sObjName=oOptions.sObjName==undefined?'oTimelinePost':oOptions.sObjName;this._iOwnerId=oOptions.iOwnerId==undefined?0:parseInt(oOptions.iOwnerId);this._sAnimationEffect=oOptions.sAnimationEffect==undefined?'slide':oOptions.sAnimationEffect;this._iAnimationSpeed=oOptions.iAnimationSpeed==undefined?'slow':oOptions.iAnimationSpeed;this._bEmoji=oOptions.bEmoji==undefined?!1:oOptions.bEmoji;this._bAutoAttach=oOptions.bAutoAttach==undefined?!1:oOptions.bAutoAttach;this._sAutoUploader=oOptions.sAutoUploader==undefined?'':oOptions.sAutoUploader;this._sAutoUploaderId=oOptions.sAutoUploaderId==undefined?'':oOptions.sAutoUploaderId;this._iLimitAttachLinks=oOptions.iLimitAttachLinks==undefined?0:oOptions.iLimitAttachLinks;this._sLimitAttachLinksErr=oOptions.sLimitAttachLinksErr==undefined?'':oOptions.sLimitAttachLinksErr;this._oAttachedLinks=oOptions.oAttachedLinks==undefined?{}:oOptions.oAttachedLinks;this._sVideosAutoplay=oOptions.sVideosAutoplay==undefined?'off':oOptions.sVideosAutoplay;this._aHtmlIds=oOptions.aHtmlIds==undefined?{}:oOptions.aHtmlIds;this._oRequestParams=oOptions.oRequestParams==undefined?{}:oOptions.oRequestParams;var $this=this;if(typeof window.glOnInitEditor==='undefined')
window.glOnInitEditor=[];if(this._bEmoji)
window.glOnInitEditor.push(function(sEditorSelector){var sBaseUrl=sUrlRoot+'plugins_public/emoji/js/';if('undefined'===typeof(EmojiPicker)){bx_get_scripts([sBaseUrl+'util.js',sBaseUrl+'config.js',sBaseUrl+'emoji-picker.js',sBaseUrl+'jquery.emojiarea.js'],function(){$this.initEmoji(sEditorSelector)})}else $this.initEmoji(sEditorSelector)});$(document).ready(function(){var oPost=$($this.sIdPost+' form');if(!oPost||oPost.length==0)
oPost=$($this.sIdPostForm);oPost.each(function(){var sId=$(this).attr('id');$this.initFormPost(sId);$this.initTrackerInsertSpace(sId);if($this._bAutoAttach)
$this.initTrackerInsertImage();})})}
BxTimelinePost.prototype=new BxTimelineMain();BxTimelinePost.prototype.initEmoji=function(sEditorSelector){if(!this._bEmoji)
return;var oLink=$(sEditorSelector).parents('form:first').find('a.add-emoji');var oEmojiConf={emojiable_selector:bx_editor_get_htmleditable(sEditorSelector),menu_icon:oLink};new EmojiPicker(oEmojiConf).discover()};BxTimelinePost.prototype.initFormPost=function(sFormId){var $this=this;var oForm=$('#'+sFormId);var oTextarea=oForm.find('textarea');autosize(oTextarea);oForm.ajaxForm({dataType:"json",beforeSubmit:function(formData,jqForm,options){window[$this._sObjName].beforeFormPostSubmit(oForm)},success:function(oData){window[$this._sObjName].afterFormPostSubmit(oForm,oData)}})};BxTimelinePost.prototype.onFormPostSubmit=function(oForm){if(this.isLockedForm($(oForm)))
return!1;return!0};BxTimelinePost.prototype.beforeFormPostSubmit=function(oForm){this.loadingInButton($(oForm).children().find(':submit'),!0)};BxTimelinePost.prototype.afterFormPostSubmit=function(oForm,oData){var $this=this;var fContinue=function(){if(oData&&oData.form!=undefined&&oData.form_id!=undefined){$('#'+oData.form_id).replaceWith(oData.form);$this.initFormPost(oData.form_id);return}
if(oData&&oData.id!=undefined){var iId=parseInt(oData.id);if(iId<=0)
return;$('.'+$this.sClassView+':visible').each(function(){var oView=$(this);$this._getPost(oView,iId,jQuery.extend({},$this._oRequestParams,{view:$this._getView(oView),afps_loading:1}))})}
$this._getForm(oForm)};this.loadingInButton($(oForm).children().find(':submit'),!1);if(oData&&oData.message!=undefined)
bx_alert(oData.message,fContinue);else fContinue()};BxTimelinePost.prototype.initFormAttachLink=function(sFormId){var $this=this;var oForm=$('#'+sFormId);oForm.ajaxForm({dataType:"json",clearForm:!0,beforeSubmit:function(formData,jqForm,options){window[$this._sObjName].beforeFormAttachLinkSubmit(oForm)},success:function(oData){window[$this._sObjName].afterFormAttachLinkSubmit(oForm,oData)}})};BxTimelinePost.prototype.beforeFormAttachLinkSubmit=function(oForm){this.loadingInButton($(oForm).children().find(':submit'),!0)};BxTimelinePost.prototype.afterFormAttachLinkSubmit=function(oForm,oData){var $this=this;var fContinue=function(){if(oData&&oData.item!=undefined){$('#'+$this._aHtmlIds.attach_link_popup).dolPopupHide({});if(!$.trim(oData.item).length)
return;$this._oAttachedLinks[oData.url]=oData.id;var iEventId=0;if(oData&&oData.event_id!=undefined)
iEventId=parseInt(oData.event_id);var oItem=$(oData.item).hide();$('#'+$this._aHtmlIds.attach_link_form_field+iEventId).prepend(oItem).find('#'+oItem.attr('id')).bx_anim('show',$this._sAnimationEffect,$this._sAnimationSpeed,function(){$(this).bxProcessHtml()});$this.unlockForm($('#'+$this._aHtmlIds.attach_link_form_field+iEventId).parents('form:first'));return}
if(oData&&oData.form!=undefined&&oData.form_id!=undefined){$('#'+oData.form_id).replaceWith(oData.form);$this.initFormAttachLink(oData.form_id);return}};this.loadingInButton($(oForm).find(':submit'),!1);if(oData&&oData.message!=undefined)
bx_alert(oData.message,fContinue);else fContinue()};BxTimelinePost.prototype.deleteAttachLink=function(oLink,iId){var $this=this;var oData=this._getDefaultData();oData.id=iId;var oAttachLink=$('#'+this._aHtmlIds.attach_link_item+iId);bx_loading(oAttachLink,!0);jQuery.post(this._sActionsUrl+'delete_attach_link/',oData,function(oData){var fContinue=function(){if(oData&&oData.code!=undefined&&oData.code==0){oAttachLink.bx_anim('hide',$this._sAnimationEffect,$this._sAnimationSpeed,function(){$(this).remove;if(oData.url!=undefined&&oData.url.length!=0)
delete $this._oAttachedLinks[oData.url]})}};bx_loading(oAttachLink,!1);if(oData&&oData.message!=undefined)
bx_alert(oData.message,fContinue);else fContinue()},'json');return!1};BxTimelinePost.prototype.showAttachLink=function(oLink,iEventId){if(this._iLimitAttachLinks!=0&&Object.keys(this._oAttachedLinks).length>=this._iLimitAttachLinks){bx_alert(this._sLimitAttachLinksErr);return!1}
var oData=this._getDefaultData();oData.event_id=iEventId;$(window).dolPopupAjax({id:{value:this._aHtmlIds.attach_link_popup,force:!0},url:bx_append_url_params(this._sActionsUri+'get_attach_link_form/',oData),closeOnOuterClick:!1,removeOnClose:!0});return!1};BxTimelinePost.prototype._getForm=function(oElement){var $this=this;var oData=this._getDefaultData();jQuery.post(this._sActionsUrl+'get_post_form/',oData,function(oData){if(oData&&oData.options!=undefined)
$this.updateOptions(oData.options);if(oData&&oData.form!=undefined&&oData.form_id!=undefined){$('#'+oData.form_id).replaceWith(oData.form);$this.initFormPost(oData.form_id)}},'json')};BxTimelinePost.prototype._onGetPost=function(oData){var $this=this;var fContinue=function(oData){if(!$.trim(oData.item).length)
return;var aTypes=Array.isArray(oData.type)?oData.type:new Array(oData.type);aTypes.forEach(function(sType){oData.type=sType;$this.oView=$($this._getHtmlId('main',oData));if(!$this.oView.length&&oData.type=='feed'){oData.type='owner_and_connections';$this.oView=$($this._getHtmlId('main',oData))}
var oLoadMore=$this.oView.find('.'+$this.sSP+'-load-more');if(!oLoadMore.is(':visible'))
oLoadMore.show();var oEmpty=$this.oView.find('.'+$this.sSP+'-empty');if(oEmpty.is(':visible'))
oEmpty.hide();var oContent=$(oData.item).bxProcessHtml();switch(oData.view){case 'timeline':var oItems=$this.oView.find('.'+$this.sClassItems);var oDivider=oItems.find('.'+$this.sClassDividerToday);var bDivider=oDivider.length>0;if(bDivider&&!oDivider.is(':visible'))
oDivider.show();oContent.hide();var oItem=bDivider?oDivider.after(oContent).next('.'+$this.sClassItem+':hidden'):oContent.prependTo(oItems);oItem.bx_anim('show',$this._sAnimationEffect,$this._iAnimationSpeed,function(){$(this).find('.bx-tl-item-text .bx-tl-content').checkOverflowHeight($this.sSP+'-overflow',function(oElement){$this.onFindOverflow(oElement)});$this.initFlickity($this.oView)});if($this._sVideosAutoplay!='off')
$this.initVideos($this.oView);break;case 'outline':$this.prependMasonry(oContent,function(oItems){$(oItems).find('.bx-tl-item-text .bx-tl-content').checkOverflowHeight($this.sSP+'-overflow',function(oElement){$this.onFindOverflow(oElement)});$this.initFlickity($this.oView)});break}})};if(oData&&oData.message!=undefined&&oData.message.length!=0)
bx_alert(oData.message,function(){fContinue(oData)});else fContinue(oData)}
 }
